### PR TITLE
Update rgpt3 functions

### PR DESCRIPTION
**Pull request by jan-abel-inwt**
see https://github.com/Pandora-IsoMemo/data-tools/issues/70

### CODE REVIEW

**Comment by jan-abel-inwt** [comment]
We need to wait for a valid api key to test the application.

There are still some Issues concerning the `logprobs` argument in the `rgpt_single()` function:

```
Error in logprobs_output$token[i] <- data_logprobs[[i]]$token : 
  replacement has length zero
```

**Comment by jan-abel-inwt** [comment]
I fixed the issue above by setting the argument `output_type` to `text` and `logprobs` to `false`.

@arunge we need to determine which arguments of the rgpt_single() function can be adjusted within the Shiny UI.

```
rgpt_single = function(prompt_role = 'user'
                          , prompt_content
                          , seed = NULL
                          , model = 'gpt-3.5-turbo-1106'
                          , output_type = 'text'
                          , max_tokens = 100
                          , temperature = 1.0
                          , top_p = 1
                          , n = 1
                          , stop = NULL
                          , presence_penalty = 0
                          , frequency_penalty = 0
                          , logprobs = FALSE
)
```

**Comment by jan-abel-inwt** [comment]
We need to handle the output of the gpt_test_completion function correctly.

Output of the `rgpt_test_completion` function with correct key:

```R
> rgpt_test_completion()
[1] ".. test successful .."
       n prompt_role                 prompt_content  gpt_role
   <num>      <char>                         <char>    <char>
1:     1        user Write a story about R Studio:  assistant
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         gpt_content
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <char>
1: Alice was a data scientist who loved exploring and analyzing data to gain valuable insights. She was always on the lookout for new tools and software that could help her in her work. That's when she came across R Studio, a powerful integrated development environment for R, a programming language used for statistical computing and graphics.\n\nExcited to try out this new tool, Alice quickly downloaded R Studio and got started. She was impressed by its user-friendly interface and the wide range of features it offered. From data visualization

> sapply(rgptout, typeof)
             n    prompt_role prompt_content       gpt_role    gpt_content 
      "double"    "character"    "character"    "character"    "character" 
```

with incorrect API key:

```R
> rgptoutfales <- rgpt_test_completion()
[1] ".. test successful .."
Warning message:
In rgpt_single(prompt_content = test_prompt, max_tokens = 100) :
  Request completed with error. Code: 401, message: Incorrect API key provided: sk-z1m8A***************************************5T9F. You can find your API key at https://platform.openai.com/account/api-keys.
  
 > sapply(rgptoutfales, typeof)
             n    prompt_role prompt_content 
      "double"    "character"    "character" 
```

**Comment by jan-abel-inwt** [comment]
This is working fine again. I have a few suggestions @arunge:

For documentation purposes - This is how the output of the `rgpt_single()` function is structured when using the `test_prompt` of the `rgpt_test_completion()`:

```R
> output <- rgpt_test_completion()
> Hmisc::list.tree(output, maxcomp=20, maxlen=80)
 output = list 3 (8880 bytes)
.  core_output = list 5( data.table data.frame )
. .  n = double 1= 1
. .  prompt_role = character 1= user 
. .  prompt_content = character 1= Write a story about R Studio:  
. .  gpt_role = character 1= assistant 
. .  gpt_content = character 1= Once upon a time, in a small town, there was a passionate young programmer named 
. A  row.names = integer 1= 1
. A  .internal.selfref = externalptr 1
.  meta_ouput = list 18( data.table data.frame )
. .  request_id = character 1= chatcmpl-99vIs2PdAXp3G13w3B5985f7RHjBM 
. .  object = character 1= chat.completion 
. .  model = character 1= gpt-3.5-turbo-1106 
. .  param_prompt_role = character 1= user 
. .  param_prompt_content = character 1= Write a story about R Studio:  
. .  param_seed = logical 1= NA
. .  param_model = character 1= gpt-3.5-turbo-1106 
. .  param_max_tokens = double 1= 100
. .  param_temperature = double 1= 1
. .  param_top_p = double 1= 1
. .  param_n = double 1= 1
. .  param_logprobs = logical 1= FALSE
. .  param_presence_penalty = double 1= 0
. .  param_frequency_penalty = double 1= 0
. .  tok_usage_prompt = integer 1= 15
. .  tok_usage_completion = integer 1= 100
. .  tok_usage_total = integer 1= 115
. .  system_fingerprint = character 1= fp_592ef5907d 
. A  row.names = integer 1= 1
. A  .internal.selfref = externalptr 1
.  logprobs_output = character 1= no logprobs requested 
```

-  Should we limit that to the `core_output` by setting `output_type=text`?

---

These are the standard arguments set in the `rgpt_single()` function:

```R
rgpt_single = function(prompt_role = 'user'
                          , prompt_content
                          , seed = NULL
                          , model = 'gpt-3.5-turbo-1106'
                          , output_type = 'complete'
                          , max_tokens = 100
                          , temperature = 1.0
                          , top_p = 1
                          , n = 1
                          , stop = NULL
                          , presence_penalty = 0
                          , frequency_penalty = 0
                          , logprobs = FALSE
)
```

- Should the user choose the model?
- Should we update to `gpt-4` model?

Available Models:

```
models = c('gpt-3.5-turbo-0125'
             , 'gpt-3.5-turbo'
             , 'gpt-3.5-turbo-1106'
             , 'gpt-3.5-turbo-16k'
             , 'gpt-3.5-turbo-0613'
             , 'gpt-3.5-turbo-16k-0613'
             , 'gpt-4'
             , 'gpt-4-0613'
             , 'gpt-4-0125-preview')
```

**Review by arunge — APPROVED** [review]
Looks good! Please check and merge:
- https://github.com/Pandora-IsoMemo/data-tools/pull/77

before merging into main. Thanks!

**Comment by arunge** [comment]
@jan-abel-inwt regarding:
> - Should the user choose the model?

For now, the feature is working as before. All additional options need to be discussed. I will open an issue for this.

> - Should we update to gpt-4 model?

Here we need to understand if there are any disadvantages if using the more recent model, or if we just can switch. We only need AI to generate valid sql requests, do you know if we should prefer one model over the other?

**Comment by jan-abel-inwt** [comment]
> Here we need to understand if there are any disadvantages if using the more recent model, or if we just can switch. We only need AI to generate valid sql requests, do you know if we should prefer one model over the other?

From the openai blog:

> Updated GPT-4 Turbo preview
Over 70% of requests from GPT-4 API customers have transitioned to GPT-4 Turbo since its release, as developers take advantage of its updated knowledge cutoff, larger 128k context windows, and lower prices. 
> 
>Today, we are releasing an updated GPT-4 Turbo preview model, gpt-4-0125-preview. This model completes tasks like code generation more thoroughly than the previous preview model and is intended to reduce cases of “laziness” where the model doesn’t complete a task. The new model also includes the fix for the bug impacting non-English UTF-8 generations.
>
> For those who want to be automatically upgraded to new GPT-4 Turbo preview versions, we are also introducing a new gpt-4-turbo-preview model name alias, which will always point to our latest GPT-4 Turbo preview model. 
>
> We plan to launch GPT-4 Turbo with vision in general availability in the coming months.

I think we should switch to the latest model, to get the best results. This would be the `gpt-4-0125-preview`. If this fine for you i switch the default model before merging.

---

@arunge, I had another idea for a possible future improvement of the results. We could experiment with some prompt engineering:

* Improve Initial prompt by giving a sample query structure
* Give contextual Information of the schema (Names of choosen Tables and Columns)

see https://innerjoin.bit.io/making-a-production-llm-prompt-for-text-to-sql-translation-b798b6e94783?gi=164cdef1b8b1

What do you think?

**Pull request merged**
